
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/party?serverTimezone=GMT
    username: root
    password: 490166948

  #redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

#  shiro:
#    session-timeout: 3600
#    cookie-timeout: 86400
#    anon_url: "/test/**,/img/**,/json/**,/images/captcha,/regist"

mybatis:
  type-aliases-package: com.tck.party.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId

