spring:
  #  jackson:
  #    serialization:
  #      FAIL_ON_EMPTY_BEANS: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/party?serverTimezone=GMT
    username: root
    password: 490166948

  #redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000


mybatis:
  type-aliases-package: com.tck.party.entity,com.tck.party.service.dto,com.tck.party.vo
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId

pagehelper:
  helper-dialect: mysql
  reasonable: false #为true时，分页数据到最后一页之后，还会继续返回最后一页的数据
  support-methods-arguments: true
  params: count=countSql

## 日志配置
logging:
  config: src/main/resources/logback.xml
#  level:
#    com.tck.party.mapper: debug

#阿里云oss
aliyun-oss:
  #bucket名称
  bucketApp: bepicolombo
  domainApp: bepicolombo.oss-cn-beijing.aliyuncs.com
  region: oss-cn-beijing
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4Fi3cz5Vuuvop85zFM9N
  accessKeySecret: bRbPqCTVyAg5uDRLNlBNyPOVwFfPuh
